### ISSUE TITLE
Undefined method assets for ...

### ISSUE THREAD

**Issue by silva96** [maglevhq/maglev-core#27]
We are not using sprockets in our app, but the engine config calls this line:

```ruby
config.assets.precompile += %w[maglev/logo.png maglev/favicon.png]
```

Which is a sprockets config. How can we skip that?
(we are using cssbundling-rails jsbundling-rails and propshaft)

**Comment by did** [comment]
👋 @silva96, I think I could get rid of sprockets in the engine that are being used only for those 2 assets.

**Comment by did** [comment]
@silva96 could you try installing the version of Maglev from the Github master branch please and see if it solves your issue?
thanks!
