### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by johnnynia** [maglevhq/maglev-core#39]
Maybe an hour ago I've remembered that I had read something in last week's Ruby Weekly about a new implementation attempt of a mountable rails CMS engine.

The crazy thing is: I correctly remembered the name – "maglev" !

Thing is: There are a couple software projects with the exact same name. Even in open source ruby space. It took me some time to get here.

What about just an innocent unique short string (like "ogep" or something)?

**Comment by megatux** [comment]
[yeah, like the Maglev Ruby VM from Gemstone](https://maglev.github.io/)...altought the repo was archived some months ago

**Comment by did** [comment]
I get that the name is being used by another Ruby gem (which is no longer maintained and outdated) but I will stick with the name Maglev. Besides, on Rubygems, I used `maglevcms` as its gem name. So I guess it's fine.
