### ISSUE TITLE
CollectionItem search uses a hardcoded `products` id

### ISSUE THREAD

**Issue by johnbeatty** [maglevhq/maglev-core#42]
I'm trying to use the collections feature to pull in an ActiveRecord model. I believe the settings for a section should determine which collection is called, but unless the collection is name products, it doesn't work, and you see a 500 error in the logs.

The API call here uses a hardcoded value, products, so the API call won't work if you have a collection of any other name. 

https://github.com/maglevhq/maglev-core/blob/fecaea7d08dba71eb3cd1cc683b1d97e84a53820/app/frontend/editor/components/kit/collection-item-input.vue#L13

Thanks for this great library! I've been looking for something like this for a while.

**Comment by did** [comment]
this is quite embarrassing :-( Anyway, thanks for taking a look at it!
I'll fix that ASAP. 
Thanks!

**Comment by did** [comment]
fixed by c76a6e5f5f78dbb50c87cd1cd7d90499697eafdf
