### ISSUE TITLE
Internal Error: maglev@workspace:.: This package doesn't seem to be present in your lockfile

### ISSUE THREAD

**Issue by work-leonid** [maglevhq/maglev-core#60]
Hi!
I am trying to install the latest version of maglev. Installing through
```bash
rails new my-awesome-site \
  -m https://raw.githubusercontent.com/maglevhq/maglev-core/master/template.rb \
  --database=postgresql \
  --skip-action-cable
```
An error appears during installation
<img width="1276" alt="image" src="https://github.com/maglevhq/maglev-core/assets/8654430/0f45b402-b8e9-40c0-8ee2-a91400fd8302">

Apparently because of this I can't get into the editor http://localhost:3000/maglev/editor/en/index
<img width="1107" alt="image" src="https://github.com/maglevhq/maglev-core/assets/8654430/568b3eea-b387-4322-a9e0-db0f2a48ce6c">

It might be a problem with my yarn (?). But to be honest I don't understand where to dig to fix this error

**Comment by did** [comment]
hey @work-leonid, it looks like a yarn/node issue. 
- first, could you try to remove all the `maglevcms` gems of your system?
- then within your Rails project, could you run `bundle exec rails maglev:maglev:vite:install_dependencies`?
- and finally, run `bundle exec rails maglev:vite:build_all`.

If errors occur, please send me the raw text logs. Thanks!

**Comment by malachaifrazier** [comment]
I was just seeing this error, so I ran:
`bundle exec rails maglev:vite:install_dependencies` and then `bundle exec rails maglev:vite:build_all`.
That seems to have corrected the OP error.
@did maybe add this bit of troubleshooting to the docs?

**Comment by did** [comment]
thanks @malachaifrazier! I've appended the first item in the troubleshooting section: https://docs.maglev.dev/guides/troubleshooting
