### ISSUE TITLE
Running Installer - Vite Compatibility Issue

### ISSUE THREAD

**Issue by rfrisch43** [maglevhq/maglev-core#61]
I'm trying to install maglev by running:

`bundle exec rails g maglev:install`

However, that throws the following error:

`/Users/XXXX/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/vite_ruby-3.3.4/lib/vite_ruby/compatibility_check.rb:24:in raise_unless_satisfied': vite-plugin-ruby@^3.1.2 might not be compatible with vite_ruby-3.3.4 (ArgumentError)`

**Comment by did** [comment]
hey @rfrisch43 👋 Which version of Maglev are you using? The `1.2.1` version should point to a recent version of vite-plugin-ruby.

**Comment by rfrisch43** [comment]
@did I was following the instructions here: https://docs.maglev.dev/quickstart 

So it was pinned to 1.1.3

Updating to 1.2.1 did solved the install issue but now I'm having other issues.

Nothing is rendered when visiting http://localhost:3000/ and http://localhost:3000/maglev/editor/en/index is erroring:

`2023-07-30 20:06:23 -0400 Read: #<TypeError: no implicit conversion of Symbol into String>`

 I'm going to try a fresh install but do you offer install guidance and if so where is the best place reach out?

Thanks!

**Comment by did** [comment]
@rfrisch43 alright, the documentation wasn't up to date. I've fixed it. Thanks a lot!

Regarding your other issue, it's related to Puma and the Vite Rack middleware. The solution is quite simple, juste upgrade Puma to the `6.x` version.

**Comment by rfrisch43** [comment]
Perfect, that fixed it, Thanks!

**Comment by brentdodell** [comment]
> I'm trying to install maglev by running:
> 
> `bundle exec rails g maglev:install`
> 
> However, that throws the following error:
> 
> `/Users/XXXX/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/vite_ruby-3.3.4/lib/vite_ruby/compatibility_check.rb:24:in raise_unless_satisfied': vite-plugin-ruby@^3.1.2 might not be compatible with vite_ruby-3.3.4 (ArgumentError)`

I'm seeing this same error on 1.7.2

> /Users/XXXX/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/vite_ruby-3.8.2/lib/vite_ruby/compatibility_check.rb:24:in `raise_unless_satisfied': vite-plugin-ruby@^5.0.0 might not be compatible with vite_ruby-3.8.2 (ArgumentError)
