### ISSUE TITLE
docs.maglev.dev/guides/i18n does not exist

### ISSUE THREAD

**Issue by sedubois** [maglevhq/maglev-core#73]
`config/initializers/maglev.rb` states `If you want add more locales to your site, use the SetSiteLocalesService (https://docs.maglev.dev/guides/i18n).`

However, https://docs.maglev.dev/guides/i18n does not exist (404) and a doc search on SetSiteLocalesService yielded no results. 

I found https://docs.maglev.dev/guides/setup-multiple-languages which does explain that to add a locale, one can run `bundle exec rails maglev:change_site_locales`.

**Comment by did** [comment]
thanks @sedubois!
