### ISSUE TITLE
Switching language while preserving site location

### ISSUE THREAD

**Issue by sedubois** [maglevhq/maglev-core#74]
If, say, a home page has an English and a French version, one could provide a language switcher as follows:
- add an "English" link pointing to /en in the French version of the home page navigation
- add a "French" link pointing to /fr in the English version of the home page navigation

However, when switching language from other pages (e.g. Careers), the viewer will then be redirected to the home page instead of being shown the Careers page in the alternate language. How to ensure each page's language switcher links to its alternative language version(s) instead of linking back home?

**Comment by did** [comment]
@sedubois I wrote some doc about it here -> https://docs.maglev.dev/guides/setup-multiple-languages#locale-switcher
