### ISSUE TITLE
How to modify frontend editor files

### ISSUE THREAD

**Issue by guerreiropedr0** [maglevhq/maglev-core#76]
I am trying to make it possible to view the entire collection_item records when the select input is empty, instead of showing no records. I wanted to override the js files so it triggers the fetch when it is empty

Is this currently possible?

**Comment by did** [comment]
@guerreiropedr0 ATM, this is not possible to override a JS component. 

I see 2 solutions to solve your problem: 
- tweak the current component `app/frontend/editor/components/kit/collection-item-input.vue` to change its behavior through a config option for instance (maybe `display_all: true|false`). 
- allow to create custom setting type (ruby + VueJS component). 

The first solution is definitively the easiest one and if you know a bit about Ruby and JS, you should be able to do it. 

The second one requires some intense thinking :-) Probably it would make sense to extract the editor JS code from the Maglev-core and create its own NPM package.
