### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by DiegoPartida7** [maglevhq/maglev-core#78]
Hi, I'm having trouble at the installation. When the task "maglev:create_site" tries to run I get the following error: 

![Screenshot 2024-03-29 at 4 26 07 p m](https://github.com/maglevhq/maglev-core/assets/47610236/5a64dd5a-2c8d-4dd3-9c94-9eea28cb4033)

I tried the installation with the short version script.

Thanks for your time!

**Comment by did** [comment]
hey @DiegoPartida7, I've just published a new version of the gem (1.6.1) and I ran a fresh new installation and everything worked smoothly (Ruby 3.1.4 + Rails 7.1.3)
Could you try again please? Thanks!
