### ISSUE TITLE
Yarn install failing

### ISSUE THREAD

**Issue by j-mcnally** [maglevhq/maglev-core#81]
rake  maglev:vite:install_dependencies
➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @vitejs/plugin-vue2@npm:2.3.1, @vue/test-utils@npm:1.3.6, autoprefixer@npm:10.4.16, axios@npm:1.6.2, and 482 more.
➤ YN0000: └ Completed in 0s 638ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ maglev@workspace:. doesn't provide lodash (p3d004), requested by camelcase-object-deep.
➤ YN0002: │ maglev@workspace:. doesn't provide postcss (p11d83), requested by autoprefixer.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0028: │ The lockfile would have been modified by this install, which is explicitly forbidden.
➤ YN0000: └ Completed
➤ YN0000: · Failed with errors in 0s 670ms

**Comment by did** [comment]
👋 @j-mcnally, my guess is that the `yarn.lock` present in the gem has been generated by Yarn 1 and you're using Yarn 4.
I'm going to see if I can reproduce it on my machine (which has an old version of Yarn) and find a workaround.
