### ISSUE TITLE
Error while following Quick start

### ISSUE THREAD

**Issue by fkoessler** [maglevhq/maglev-core#82]
Trying to add Maglev to an existing Rails project.

Requirements are respected:
- rails (7.0.4.2)
- ruby 3.1.3
- using a postgresql 16 database
- Node 18.14.2

I added Maglev to the Gemfile:
```

gem 'maglevcms', '~> 1.5.1'
gem 'maglevcms-hyperui-kit', '~> 1.1.0'
```

and ran bundle install:
```

    maglevcms (1.5.1)
      jbuilder (~> 2.11.2)
      kaminari (~> 1.2.1)
      maglev-injectable (~> 2.1.1)
      rails (>= 6, < 7.2)
      vite_rails (>= 3, < 4)
      vite_ruby (>= 3.5)
    maglevcms-hyperui-kit (1.1.0)
```

Now when trying to setup Maglev with: `bundle exec rails g maglev:install`

The following error is raised:

> $ bundle exec rails g maglev:install
> /home/francois/.rvm/gems/ruby-3.1.3@project/gems/maglevcms-1.5.1/app/services/maglev/app_container.rb:21:in `<class:AppContainer>': uninitialized constant Maglev::FetchSectionScreenshotUrl (NameError)
> 
>     dependency :fetch_section_screenshot_url, class: Maglev::FetchSectionScreenshotUrl,
>                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Did you mean?  Maglev::FetchSectionScreenshotURL
>                Maglev::FetchSectionScreenshotPath

**Comment by did** [comment]
hey @fkoessler! By any chance, didn't you add a new entry in your `config/inflections.rb` related to the **url** keyword? Something like:
```
inflect.acronym "URL"
```

**Comment by did** [comment]
👋 @fkoessler, you're using an old version of Maglev. Could you try it from scratch with the `1.6.1`version  instead please? 
Btw, I've updated the documentation site accordingly. Thanks!

**Comment by fkoessler** [comment]
@did, all good using maglevcms `1.6.1`, thanks for the support!
