### ISSUE TITLE
[Pro] Yarn install failing on node-sass

### ISSUE THREAD

**Issue by j-mcnally** [maglevhq/maglev-core#83]
yarn install
➤ YN0087: Migrated your project to the latest Yarn version 🚀

➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @babel/plugin-proposal-optional-chaining@npm:7.12.7, @rails/webpacker@npm:5.2.1, axios@npm:0.21.1, and 1170 more.
➤ YN0000: └ Completed in 0s 670ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ maglev@workspace:. doesn't provide @babel/core (pbed2e), requested by @babel/plugin-proposal-optional-chaining.
➤ YN0002: │ maglev@workspace:. doesn't provide css-loader (p5de7b), requested by vue-loader.
➤ YN0002: │ maglev@workspace:. doesn't provide lodash (p0a901), requested by camelcase-object-deep.
➤ YN0002: │ maglev@workspace:. doesn't provide webpack (p7d06c), requested by webpack-dev-server.
➤ YN0002: │ maglev@workspace:. doesn't provide webpack (pf40f7), requested by vue-loader.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 1006 packages were added to the project (+ 185.6 MiB).
➤ YN0000: └ Completed in 5s 323ms
➤ YN0000: ┌ Link step
➤ YN0007: │ core-js@npm:3.8.3 must be built because it never has been before or the last one failed
➤ YN0007: │ node-sass@npm:4.14.1 must be built because it never has been before or the last one failed
➤ YN0007: │ fsevents@patch:fsevents@npm%3A1.2.13#optional!builtin<compat/fsevents>::version=1.2.13&hash=d11327 must be built because it never has been before or the last one failed
➤ YN0009: │ node-sass@npm:4.14.1 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/fd/04qkytls0xxc3nhjyccdw3vm0000gn/T/xfs-4bd31f96/build.log)
➤ YN0000: └ Completed in 3s 953ms
➤ YN0000: · Failed with errors in 10s 32ms

**Comment by j-mcnally** [comment]
Failing to install node-sass because i dont have python 2

**Comment by j-mcnally** [comment]
ok tried again with python2 and still not working... trying to isolate the dep and upgrade that instead

**Comment by j-mcnally** [comment]
i eventually forced it through by yarn adding sass-loader and then re-running yarn install. lets see if vite builds.

**Comment by j-mcnally** [comment]
ok that works for now, but i'd love to figure out how to fix these yarn problems incase they cause issues when we go to prod.

**Comment by did** [comment]
Issue with MaglevPRO only
