### ISSUE TITLE
Bump version for Rails 8 support

### ISSUE THREAD

**Issue by malakada** [maglevhq/maglev-core#97]
I saw that you added Rails 8 support via #95 two weeks ago, but the latest released version (1.7.3) was released on Sep 17 (~3 months ago).

It'd be pretty cool of yall to bump that version number. 😌

**Comment by henrikbjorn** [comment]
@did Possible to cut a new release? :)

**Comment by did** [comment]
👋 @malakada & @henrikbjorn, sure, I'll do that tomorrow. I need to fix one quick JS issue before releasing the new version.

**Comment by did** [comment]
🎉 commit 9e9937e4
